import { Course, CourseLevel } from './types';

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Data Science Fundamentals',
    description: 'An introduction to the world of data science, covering statistics, probability, and basic Python programming.',
    instructor: 'Dr. Sarah Chen',
    duration: '8 Weeks',
    level: CourseLevel.BEGINNER,
    price: 499,
    tags: ['Python', 'Statistics', 'Data Analysis'],
    image: 'https://picsum.photos/id/1/800/600',
  },
  {
    id: 'c2',
    title: 'Advanced Machine Learning',
    description: 'Deep dive into neural networks, deep learning, and natural language processing using TensorFlow and PyTorch.',
    instructor: 'Prof. James Miller',
    duration: '12 Weeks',
    level: CourseLevel.ADVANCED,
    price: 899,
    tags: ['AI', 'Machine Learning', 'TensorFlow'],
    image: 'https://picsum.photos/id/2/800/600',
  },
  {
    id: 'c3',
    title: 'Business Intelligence with Power BI',
    description: 'Learn to create stunning dashboards and actionable insights using Microsoft Power BI.',
    instructor: 'Emily Davis',
    duration: '6 Weeks',
    level: CourseLevel.INTERMEDIATE,
    price: 399,
    tags: ['Power BI', 'Visualization', 'Business'],
    image: 'https://picsum.photos/id/3/800/600',
  },
  {
    id: 'c4',
    title: 'SQL for Data Analysis',
    description: 'Master the art of querying databases. Learn complex joins, window functions, and database optimization.',
    instructor: 'Michael Ross',
    duration: '4 Weeks',
    level: CourseLevel.BEGINNER,
    price: 299,
    tags: ['SQL', 'Database', 'Backend'],
    image: 'https://picsum.photos/id/4/800/600',
  },
  {
    id: 'c5',
    title: 'Predictive Analytics for Finance',
    description: 'Apply statistical algorithms and machine learning techniques to identify the likelihood of future financial outcomes.',
    instructor: 'Robert Zhang',
    duration: '10 Weeks',
    level: CourseLevel.ADVANCED,
    price: 750,
    tags: ['Finance', 'Forecasting', 'R'],
    image: 'https://picsum.photos/id/5/800/600',
  },
  {
    id: 'c6',
    title: 'Data Engineering Essentials',
    description: 'Learn how to build and maintain the infrastructure required for optimal extraction, transformation, and loading (ETL) of data.',
    instructor: 'Lisa Wong',
    duration: '10 Weeks',
    level: CourseLevel.INTERMEDIATE,
    price: 650,
    tags: ['ETL', 'Big Data', 'Cloud'],
    image: 'https://picsum.photos/id/6/800/600',
  }
];
